# Branch Protection Rules for Auto-Merge
# This file defines the protection rules that must be satisfied before auto-merge can occur

# Main branch protection
main:
  required_status_checks:
    strict: true
    contexts:
      - "Code Quality & Performance"
      - "Vercel Deployment Pipeline"
  required_pull_request_reviews:
    required_approving_review_count: 1
    dismiss_stale_reviews: true
    require_code_owner_reviews: false
    require_last_push_approval: true
  enforce_admins: false
  allow_force_pushes: false
  allow_deletions: false
  block_creations: false
  required_conversation_resolution: true
  require_linear_history: false
  lock_branch: false

# Develop branch protection
develop:
  required_status_checks:
    strict: true
    contexts:
      - "Code Quality & Performance"
      - "Vercel Deployment Pipeline"
  required_pull_request_reviews:
    required_approving_review_count: 1
    dismiss_stale_reviews: true
    require_code_owner_reviews: false
    require_last_push_approval: true
  enforce_admins: false
  allow_force_pushes: false
  allow_deletions: false
  block_creations: false
  required_conversation_resolution: true
  require_linear_history: false
  lock_branch: false

# Feature branch protection (for any feature/* branches)
feature/*:
  required_status_checks:
    strict: true
    contexts:
      - "Code Quality & Performance"
  required_pull_request_reviews:
    required_approving_review_count: 1
    dismiss_stale_reviews: true
    require_code_owner_reviews: false
    require_last_push_approval: true
  enforce_admins: false
  allow_force_pushes: false
  allow_deletions: false
  block_creations: false
  required_conversation_resolution: true
  require_linear_history: false
  lock_branch: false
