
[deployment]
build = ["npm", "run", "build"]
staticFiles = "out"
publicDir = "out"
deploymentTarget = "static"

[nix]
channel = "stable-24_05"

[env]
NODE_ENV = "production"

[[ports]]
localPort = 5000
externalPort = 80
